"""Add email verification fields to User model

Revision ID: 416b2ab5d572
Revises: 715ba1e4d2df
Create Date: 2025-10-17 00:08:02.961480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '416b2ab5d572'
down_revision = '715ba1e4d2df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('verification_code', sa.String(length=16), nullable=True))
    
    # Set admin user as verified
    op.execute("UPDATE users SET email_verified = 1 WHERE email = 'prettyraradza@gmail.com'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_code')
        batch_op.drop_column('email_verified')
    # ### end Alembic commands ###
