"""Add username to User model

Revision ID: 715ba1e4d2df
Revises: 2111f7b66c18
Create Date: 2025-10-14 00:48:22.891867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715ba1e4d2df'
down_revision = '2111f7b66c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
